### ISSUE TITLE
serialize issue

### ISSUE THREAD

**Issue by InTheBottle** [Mutagen-Modding/Spriggit#101]
[14:32:12.730 INF] Attempting to gather dependency information for package 'Spriggit.Json.Skyrim.0.36.13' with respect to project 'C:\Users\ronni\AppData\Local\Temp\szltldhz.5yn', targeting 'Any,Version=v0.0'
[14:32:12.927 INF] Gathering dependency information took 193 ms
[14:32:27.326 INF] Attempting to resolve dependencies for package 'Spriggit.Json.Skyrim.0.36.13' with DependencyBehavior 'Lowest'
[14:32:27.336 INF] Resolving dependency information took 0 ms
[14:32:27.337 INF] Resolving actions to install package 'Spriggit.Json.Skyrim.0.36.13'
[14:32:27.338 INF] Resolved actions to install package 'Spriggit.Json.Skyrim.0.36.13'
[14:32:27.351 INF] Testing Undefined null Retrieving package 'Spriggit.Json.Skyrim 0.36.13' from 'nuget.org'.
[14:32:27.368 WRN] Install failed. Rolling back...
[14:32:27.369 INF] Executing nuget actions took 22 ms
[14:32:27.371 ERR] Error preparing plugin folder
NuGet.Packaging.Core.PackagingException: Package 'Spriggit.Json.Skyrim 0.36.13' has a package type 'DotnetTool' that is not supported by project 'C:\Users\ronni\AppData\Local\Temp\szltldhz.5yn'.
   at NuGet.PackageManagement.InstallationCompatibility.EnsurePackageCompatibility(NuGetProject nuGetProject, PackageIdentity packageIdentity, NuspecReader nuspecReader)
   at NuGet.PackageManagement.InstallationCompatibility.EnsurePackageCompatibilityAsync(NuGetProject nuGetProject, PackageIdentity packageIdentity, DownloadResourceResult resourceResult, CancellationToken cancellationToken)
   at NuGet.PackageManagement.NuGetPackageManager.ExecuteInstallAsync(NuGetProject nuGetProject, PackageIdentity packageIdentity, DownloadResourceResult resourceResult, HashSet1 packageWithDirectoriesToBeDeleted, INuGetProjectContext nuGetProjectContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.ExecuteNuGetProjectActionsAsync(NuGetProject nuGetProject, IEnumerable1 nuGetProjectActions, INuGetProjectContext nuGetProjectContext, PackageDownloadContext downloadContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.ExecuteNuGetProjectActionsAsync(NuGetProject nuGetProject, IEnumerable1 nuGetProjectActions, INuGetProjectContext nuGetProjectContext, PackageDownloadContext downloadContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.ExecuteNuGetProjectActionsAsync(NuGetProject nuGetProject, IEnumerable1 nuGetProjectActions, INuGetProjectContext nuGetProjectContext, PackageDownloadContext downloadContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.InstallPackageAsync(NuGetProject nuGetProject, PackageIdentity packageIdentity, ResolutionContext resolutionContext, INuGetProjectContext nuGetProjectContext, PackageDownloadContext downloadContext, IEnumerable1 primarySources, IEnumerable1 secondarySources, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.InstallPackageAsync(NuGetProject nuGetProject, PackageIdentity packageIdentity, ResolutionContext resolutionContext, INuGetProjectContext nuGetProjectContext, IEnumerable1 primarySources, IEnumerable1 secondarySources, CancellationToken token)
   at Spriggit.Engine.Services.Singletons.NugetDownloader.RestoreFor(PackageIdentity identity, DirectoryPath packagesPath, CancellationToken cancel) in D:\a\Spriggit\Spriggit\Spriggit.Engine\Services\Singletons\NugetDownloader.cs:line 122
   at Spriggit.Engine.Services.Singletons.PreparePluginFolder.Prepare(PackageIdentity ident, CancellationToken cancellationToken, DirectoryPath targetDir) in D:\a\Spriggit\Spriggit\Spriggit.Engine\Services\Singletons\PreparePluginFolder.cs:line 41
   at Spriggit.Engine.Services.Singletons.ConstructEntryPoint.ConstructFor(DirectoryPath tempPath, PackageIdentity ident, CancellationToken cancellationToken, Boolean shouldRetry) in D:\a\Spriggit\Spriggit\Spriggit.Engine\Services\Singletons\ConstructEntryPoint.cs:line 66
[14:32:27.380 WRN] Cached NULL entry point for Spriggit.Json.Skyrim.0.36.13
Error:
System.NotSupportedException: Could not locate entry point for: SpriggitMeta { Source = Spriggit.Json, Release = SkyrimSE }
   at Spriggit.Engine.Services.Singletons.SpriggitEngine.Serialize(ModPath bethesdaPluginPath, DirectoryPath outputFolder, Nullable1 dataPath, Boolean postSerializeChecks, IEngineEntryPoint entryPt, SpriggitMeta meta, Nullable1 cancel) in D:\a\Spriggit\Spriggit\Spriggit.Engine\Services\Singletons\SpriggetEngine.cs:line 56
   at Spriggit.CLI.Lib.EngineRunner.Run(SerializeCommand serializeCommand, IEngineEntryPoint entryPoint) in D:\a\Spriggit\Spriggit\Spriggit.CLI.Lib\EngineRunner.cs:line 64
   at Program.<>c.<<<Main>$>b__0_1>d.MoveNext() in D:\a\Spriggit\Spriggit\Spriggit.CLI\Program.cs:line 28
--- End of stack trace from previous location ---
   at Program.<Main>$(String[] args) in D:\a\Spriggit\Spriggit\Spriggit.CLI\Program.cs:line 18
Could not locate entry point for: SpriggitMeta { Source = Spriggit.Json, Release = SkyrimSE }
   at Spriggit.Engine.Services.Singletons.SpriggitEngine.Serialize(ModPath bethesdaPluginPath, DirectoryPath outputFolder, Nullable1 dataPath, Boolean postSerializeChecks, IEngineEntryPoint entryPt, SpriggitMeta meta, Nullable1 cancel) in D:\a\Spriggit\Spriggit\Spriggit.Engine\Services\Singletons\SpriggetEngine.cs:line 56
   at Spriggit.CLI.Lib.EngineRunner.Run(SerializeCommand serializeCommand, IEngineEntryPoint entryPoint) in D:\a\Spriggit\Spriggit\Spriggit.CLI.Lib\EngineRunner.cs:line 64
   at Program.<>c.<<<Main>$>b__0_1>d.MoveNext() in D:\a\Spriggit\Spriggit\Spriggit.CLI\Program.cs:line 28
--- End of stack trace from previous location ---

Unsure what happened, one day it decided to stop working when trying to serialize plugin changes. Tried debugging on my own but couldn't figure it out. If you need more info, let me know thanks for taking a look.

**Comment by Noggog** [comment]
What UI/CLI version of spriggit are you using?  Can you confirm you're using the latest?

**Comment by InTheBottle** [comment]
Yeah, user error on my end. Sorry for the false report
