### ISSUE TITLE
Could not locate entry point for: SpriggitMeta { Source = Spriggit.yaml, Release = Starfield }

### ISSUE THREAD

**Issue by yak3d** [Mutagen-Modding/Spriggit#49]
When trying to serialize an ESM from Starfield, I receive the error below. It's the same error in the UI. It works fine for a Fallout 4 ESM though.

```
[12:30:14.987 INF] Spriggit version 0.18.0+5a68a8cad
[12:30:14.990 INF] Getting entry point for SpriggitMeta { Source = TestBooks.yaml, Release = Starfield }
[12:30:14.996 INF] Getting first identity for SpriggitMeta { Source = TestBooks.yaml, Release = Starfield }
[12:30:14.998 INF] No version specified.  Checking NuGet repositories for latest version
[12:30:14.998 INF]   Looking in repo nuget.org
[12:30:15.139 INF]   GET https://api.nuget.org/v3-flatcontainer/testbooks.yaml.starfield/index.json
[12:30:15.364 INF]   NotFound https://api.nuget.org/v3-flatcontainer/testbooks.yaml.starfield/index.json 222ms
[12:30:15.372 INF]   Looking in repo Microsoft Visual Studio Offline Packages
[12:30:15.381 INF] No version specified.  Checking NuGet repositories for latest version
[12:30:15.382 INF]   Looking in repo nuget.org
[12:30:15.384 INF]   GET https://api.nuget.org/v3-flatcontainer/testbooks.yaml/index.json
[12:30:15.507 INF]   NotFound https://api.nuget.org/v3-flatcontainer/testbooks.yaml/index.json 122ms
[12:30:15.508 INF]   Looking in repo Microsoft Visual Studio Offline Packages
[12:30:15.509 WRN] Could not get identity for SpriggitMeta { Source = TestBooks.yaml, Release = Starfield }
it\Spriggit.Engine\SpriggetEngine.cs:line 40
   at Spriggit.CLI.Runner.Run(SerializeCommand serializeCommand) in D:\a\Spriggit\Spriggit\Spriggit.CLI.Lib\Runner.cs:line 91
   at Program.<>c.<<<Main>$>b__0_1>d.MoveNext() in D:\a\Spriggit\Spriggit\Spriggit.CLI\Program.cs:line 12
--- End of stack trace from previous location ---
   at Program.<Main>$(String[] args) in D:\a\Spriggit\Spriggit\Spriggit.CLI\Program.cs:line 9
   at Program.<Main>(String[] args)
```

I tried v0.17 and v0.18.

**Comment by yak3d** [comment]
This ended up being a malformed BOOK record in my ESM. I resolved the issues in the record and it was able to parse just fine.

**Comment by Noggog** [comment]
Just for any future readers, there was also the issue of specifying a `PackageName` in the CLI command for a package that didn't exist
`--PackageName TestBooks.yaml`

This was where the original error posted came from, where it could not find the package to use.   I think the log warning could be improved a bit, as the wording `Could not get identity for SpriggitMeta` isn't great
