### ISSUE TITLE
Initial TryGetMetaInfo call should be via current version's package

### ISSUE THREAD

**Issue by Noggog** [Mutagen-Modding/Spriggit#55]
Unhandled exception. Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: The best overloaded method match for 'Spriggit.Yaml.Skyrim.EntryPoint.TryGetMetaInfo(string, Noggog.WorkEngine.IWorkDropoff, System.IO.Abstractions.IFileSystem, Noggog.IO.ICreateStream, System.Threading.CancellationToken)' has some invalid arguments
   at CallSite.Target(Closure, CallSite, Object, String, IWorkDropoff, IFileSystem, ICreateStream, CancellationToken)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute6[T0,T1,T2,T3,T4,T5,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at Spriggit.Core.DynamicEntryPoint.TryGetMetaInfo(String inputPath, IWorkDropoff workDropoff, IFileSystem fileSystem, ICreateStream streamCreator, CancellationToken cancel) in D:\a\Spriggit\Spriggit\Spriggit.Core\DynamicEntryPoint.cs:line 71
   at Spriggit.Engine.EngineEntryPoint.TryGetMetaInfo(String inputPath, IWorkDropoff workDropoff, IFileSystem fileSystem, ICreateStream streamCreator, CancellationToken cancel) in D:\a\Spriggit\Spriggit\Spriggit.Engine\EngineEntryPoint.cs:line 73
   at Spriggit.Engine.GetMetaToUse.Get(SpriggitSource source, String spriggitPluginPath, CancellationToken cancel) in D:\a\Spriggit\Spriggit\Spriggit.Engine\GetMetaToUse.cs:line 41
   at Spriggit.Engine.SpriggitEngine.Deserialize(String spriggitPluginPath, FilePath outputFile, SpriggitSource source, CancellationToken cancel) in D:\a\Spriggit\Spriggit\Spriggit.Engine\SpriggetEngine.cs:line 68
   at Spriggit.CLI.Runner.Run(DeserializeCommand deserializeCommand) in D:\a\Spriggit\Spriggit\Spriggit.CLI.Lib\Runner.cs:line 56
   at Program.<>c.<<<Main>$>b__0_0>d.MoveNext() in D:\a\Spriggit\Spriggit\Spriggit.CLI\Program.cs:line 11

**Comment by Noggog** [comment]
This has been addressed in v0.20 by having a separate `spriggit.meta` file that exists outside the translation package's files.  As such, a default entry point is no longer needed

1534ad6d7bffa9116fb0a655f5e395557fecff33
