### ISSUE TITLE
Spriggit 0.18 suddenly stopped working with strange exception

### ISSUE THREAD

**Issue by JasonJShuler** [Mutagen-Modding/Spriggit#58]
Two days ago everthing was fine, and today I can't serializing anything with the same error:
System.ArgumentException: Object of type 'Mutagen.Bethesda.Plugins.ModPath' cannot be converted to type 'Mutagen.Bethesda.Plugins.ModPath'.

Looking at the logs, it seems it is pulling a nuget package at runtime (doesn't sound typical) with mismatched version numbers - could that be the cause? I see no configuration option in the json or xml I could use to fix this... so I'm kinda blocked at the moment.

```
2024-05-21 00:14:13.526 -04:00 [INF] ================================================================
2024-05-21 00:14:13.530 -04:00 [INF] ============== Opening Spriggit v0.18.0+5a68a8cad ==============
2024-05-21 00:14:13.530 -04:00 [INF] ================================================================
2024-05-21 00:14:13.530 -04:00 [INF] 05/21/2024 00:14:13
2024-05-21 00:14:13.530 -04:00 [INF] Start Path: C:\Users\user\Downloads\Spriggit1\Spriggit.exe
2024-05-21 00:14:13.530 -04:00 [INF] Args: 
2024-05-21 00:14:13.533 -04:00 [INF] Loading settings
2024-05-21 00:14:13.534 -04:00 [INF] Loaded settings
2024-05-21 00:14:13.543 -04:00 [INF] Setting Main VM
2024-05-21 00:14:13.543 -04:00 [INF] Set Main VM
2024-05-21 00:14:13.543 -04:00 [INF] Initializing Main VM
2024-05-21 00:14:13.543 -04:00 [INF] Initialized Main VM
2024-05-21 00:15:31.328 -04:00 [INF]   CACHE https://api.nuget.org/v3-flatcontainer/spriggit.yaml.starfield/index.json
2024-05-21 00:15:31.358 -04:00 [INF] Getting first identity for SpriggitMeta { Source = Spriggit.Yaml.Starfield.0.19.0, Release = Starfield }
2024-05-21 00:15:31.362 -04:00 [INF] Cached first identity for SpriggitMeta { Source = Spriggit.Yaml.Starfield.0.19.0, Release = Starfield }: Spriggit.Yaml.Starfield.0.19.0
2024-05-21 00:15:31.364 -04:00 [INF] Constructing entry point for Spriggit.Yaml.Starfield.0.19.0
2024-05-21 00:15:31.365 -04:00 [INF] Finding target framework for C:\Users\user\AppData\Local\Temp\Spriggit\Sources\Spriggit.Yaml.Starfield.0.19.0\Spriggit.Yaml.Starfield.0.19.0\lib
2024-05-21 00:15:31.367 -04:00 [INF] Getting target framework directory for C:\Users\user\AppData\Local\Temp\Spriggit\Sources\Spriggit.Yaml.Starfield.0.19.0\Spriggit.Yaml.Starfield.0.19.0
2024-05-21 00:15:31.367 -04:00 [INF] Framework directory located: C:\Users\user\AppData\Local\Temp\Spriggit\Sources\Spriggit.Yaml.Starfield.0.19.0\Spriggit.Yaml.Starfield.0.19.0\lib\net7.0
2024-05-21 00:15:31.368 -04:00 [INF] Loading plugin: C:\Users\user\AppData\Local\Temp\Spriggit\Sources\Spriggit.Yaml.Starfield.0.19.0\Spriggit.Yaml.Starfield.0.19.0\lib\net7.0\Spriggit.Yaml.Starfield.dll
2024-05-21 00:15:31.376 -04:00 [INF] Retrieving default assembly
2024-05-21 00:15:31.380 -04:00 [INF] Trying to create entry point object
2024-05-21 00:15:31.380 -04:00 [INF] Finding entry point type
2024-05-21 00:15:31.380 -04:00 [INF] Looking for typically named entry point classes
2024-05-21 00:15:31.382 -04:00 [INF] Trying to create simplistic entry point object
2024-05-21 00:15:31.382 -04:00 [INF] Finding simplistic entry point type
2024-05-21 00:15:31.383 -04:00 [INF] Looking for typically named simplistic entry point classes
2024-05-21 00:15:31.383 -04:00 [INF] Cached entry point for Spriggit.Yaml.Starfield.0.19.0
2024-05-21 00:15:35.824 -04:00 [INF] Syncing from Mod to Git. C:\Program Files (x86)\Steam\steamapps\common\Starfield\Data\example.esm -> C:\mods\example
2024-05-21 00:15:35.825 -04:00 [INF] Spriggit version 0.18.0+5a68a8cad
2024-05-21 00:15:35.825 -04:00 [INF] Getting entry point for SpriggitMeta { Source = Spriggit.Yaml.Starfield.0.19.0, Release = Starfield }
2024-05-21 00:15:35.826 -04:00 [INF] Starting to serialize from C:\Program Files (x86)\Steam\steamapps\common\Starfield\Data\example.esm to C:\mods\example.testing with SpriggitMeta { Source = Spriggit.Yaml.Starfield.0.19.0, Release = Starfield }
2024-05-21 00:15:35.851 -04:00 [ERR] Error syncing to Git
System.ArgumentException: Object of type 'Mutagen.Bethesda.Plugins.ModPath' cannot be converted to type 'Mutagen.Bethesda.Plugins.ModPath'.
   at System.RuntimeType.CheckValue(Object& value, ParameterCopyBackAction& copyBack, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Span`1 copyOfParameters, IntPtr* byrefParameters, Span`1 shouldCopyBack, ReadOnlySpan`1 parameters, RuntimeType[] sigTypes, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.InvokeWithManyArguments(RuntimeMethodInfo mi, Int32 argCount, Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Spriggit.Core.DynamicEntryPoint.Serialize(ModPath modPath, DirectoryPath outputDir, GameRelease release, IWorkDropoff workDropoff, IFileSystem fileSystem, ICreateStream streamCreator, SpriggitSource meta, CancellationToken cancel) in D:\a\Spriggit\Spriggit\Spriggit.Core\DynamicEntryPoint.cs:line 29
   at Spriggit.Engine.AssemblyLoadedEntryPoint.Serialize(ModPath modPath, DirectoryPath outputDir, GameRelease release, IWorkDropoff workDropoff, IFileSystem fileSystem, ICreateStream streamCreator, SpriggitSource meta, CancellationToken cancel) in D:\a\Spriggit\Spriggit\Spriggit.Engine\AssemblyLoadedEntryPoint.cs:line 33
   at Spriggit.Engine.SpriggitEngine.Serialize(FilePath bethesdaPluginPath, DirectoryPath outputFolder, SpriggitMeta meta, CancellationToken cancel) in D:\a\Spriggit\Spriggit\Spriggit.Engine\SpriggetEngine.cs:line 43
   at Spriggit.UI.ViewModels.Transient.LinkVm.SyncToGit(CancellationToken cancel) in D:\a\Spriggit\Spriggit\Spriggit.UI\ViewModels\Transient\LinkVm.cs:line 211
2024-05-21 00:15:51.671 -04:00 [INF] Disposing container
```

**Comment by JasonJShuler** [comment]
So I tried using Spriggit.Yaml.Starfield as the package and specifying version 0.18.0. it seems to load right but when I attempt to do the conversion, it tried to reference the files in a non-existent path:

```
2024-05-21 01:17:44.938 -04:00 [INF] ================================================================
2024-05-21 01:17:44.942 -04:00 [INF] ============== Opening Spriggit v0.18.0+5a68a8cad ==============
2024-05-21 01:17:44.942 -04:00 [INF] ================================================================
2024-05-21 01:17:44.942 -04:00 [INF] 05/21/2024 01:17:44
2024-05-21 01:17:44.942 -04:00 [INF] Start Path: C:\Users\user\Downloads\Spriggit1\Spriggit.exe
2024-05-21 01:17:44.942 -04:00 [INF] Args: 
2024-05-21 01:17:45.104 -04:00 [INF] Getting first identity for SpriggitMeta { Source = spriggit.yaml.starfield.0.18.0, Release = Starfield }
2024-05-21 01:17:45.107 -04:00 [INF] Loading settings
2024-05-21 01:17:45.115 -04:00 [INF] Loaded settings
2024-05-21 01:17:45.115 -04:00 [INF] Setting Main VM
2024-05-21 01:17:45.115 -04:00 [INF] Set Main VM
2024-05-21 01:17:45.115 -04:00 [INF] Initializing Main VM
2024-05-21 01:17:45.115 -04:00 [INF] Initialized Main VM
2024-05-21 01:17:45.117 -04:00 [INF] Cached first identity for SpriggitMeta { Source = spriggit.yaml.starfield.0.18.0, Release = Starfield }: spriggit.yaml.starfield.Starfield.0.18.0
2024-05-21 01:17:45.120 -04:00 [INF] Constructing entry point for spriggit.yaml.starfield.Starfield.0.18.0
2024-05-21 01:17:45.123 -04:00 [INF] Restoring for spriggit.yaml.starfield.Starfield.0.18.0 at C:\Users\user\AppData\Local\Temp\mp4mmpzt.5ut
2024-05-21 01:17:45.137 -04:00 [INF] 

2024-05-21 01:17:45.157 -04:00 [INF] Attempting to gather dependency information for package 'spriggit.yaml.starfield.Starfield.0.18.0' with respect to project 'C:\Users\user\AppData\Local\Temp\mp4mmpzt.5ut', targeting 'Any,Version=v0.0'
2024-05-21 01:17:45.418 -04:00 [INF] Issue restoring for spriggit.yaml.starfield.Starfield.0.18.0 in C:\Users\user\AppData\Local\Temp\mp4mmpzt.5ut
2024-05-21 01:17:45.418 -04:00 [INF] Finding target framework for C:\Users\user\AppData\Local\Temp\mp4mmpzt.5ut\spriggit.yaml.starfield.Starfield.0.18.0\lib
2024-05-21 01:17:51.505 -04:00 [INF] Syncing from Mod to Git. C:\Program Files (x86)\Steam\steamapps\common\Starfield\Data\exampleModule.esm -> C:\mods\exampleModule
2024-05-21 01:17:51.506 -04:00 [INF] Spriggit version 0.18.0+5a68a8cad
2024-05-21 01:17:51.507 -04:00 [INF] Getting entry point for SpriggitMeta { Source = spriggit.yaml.starfield.0.18.0, Release = Starfield }
2024-05-21 01:17:51.507 -04:00 [ERR] Error syncing to Git
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\user\AppData\Local\Temp\mp4mmpzt.5ut\spriggit.yaml.starfield.Starfield.0.18.0\lib'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Abstractions.DirectoryWrapper.EnumerateDirectories(String path)
   at Spriggit.Engine.ConstructEntryPoint.PreparePluginFolder(PackageIdentity ident, CancellationToken cancellationToken, DirectoryPath targetDir) in D:\a\Spriggit\Spriggit\Spriggit.Engine\ConstructEntryPoint.cs:line 104
   at Spriggit.Engine.ConstructEntryPoint.ConstructFor(PackageIdentity ident, CancellationToken cancellationToken) in D:\a\Spriggit\Spriggit\Spriggit.Engine\ConstructEntryPoint.cs:line 52
   at Spriggit.Engine.EntryPointCache.<>c__DisplayClass8_0.<<GetFor>b__0>d.MoveNext() in D:\a\Spriggit\Spriggit\Spriggit.Engine\EntryPointCache.cs:line 65
--- End of stack trace from previous location ---
   at Noggog.TaskExt.WithCancellation[T](Task`1 task, CancellationToken token) in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Extensions\TaskExt.cs:line 191
   at Spriggit.Engine.EntryPointCache.GetFor(PackageIdentity ident, CancellationToken cancel) in D:\a\Spriggit\Spriggit\Spriggit.Engine\EntryPointCache.cs:line 80
   at Spriggit.Engine.EntryPointCache.GetFor(SpriggitMeta meta, CancellationToken cancel) in D:\a\Spriggit\Spriggit\Spriggit.Engine\EntryPointCache.cs:line 51
   at Spriggit.Engine.SpriggitEngine.Serialize(FilePath bethesdaPluginPath, DirectoryPath outputFolder, SpriggitMeta meta, CancellationToken cancel) in D:\a\Spriggit\Spriggit\Spriggit.Engine\SpriggetEngine.cs:line 39
   at Spriggit.UI.ViewModels.Transient.LinkVm.SyncToGit(CancellationToken cancel) in D:\a\Spriggit\Spriggit\Spriggit.UI\ViewModels\Transient\LinkVm.cs:line 211
2024-05-21 01:19:34.235 -04:00 [INF] Disposing container
```

**Comment by JasonJShuler** [comment]
Update: yaml to esm doesn't work at all if the custom provider is used (or non-latest version is selected) - in both 0.18 and 0.19 codebase

**Comment by Noggog** [comment]
> Opening Spriggit v0.18.0+5a68a8cad

Until spriggit stabilizes on 1.0, I'd recommend updating the UI/CLI exe itself to the newest versions when possible.  See if it does better.  Still a few improvements to be made so that the UI/CLI doesn't need to be so aggressively updated on every release

**Comment by JasonJShuler** [comment]
Once I figure out how to get it to build I should be able to stop bugging you so much - VS2022 gives one error, vscode gives a different one altogether lol.

**Comment by JasonJShuler** [comment]
Upgraded to spriggit 0.19.0 UI and changed to use 0.18.0 model; problems solved. Thanks!

**Comment by JasonJShuler** [comment]
FYI - 0.19.0 is now working fine with the latest model. Thanks!

**Comment by DJLegends1011** [comment]
hmm gotten this same issue but for 0.24 any help would be great
