### ISSUE TITLE
Double check spriggit temp folder recovery

### ISSUE THREAD

**Issue by Noggog** [Mutagen-Modding/Spriggit#68]
User had:
```
2024-06-21 18:49:16.987 -04:00 [ERR] Error syncing to Git
System.TypeInitializationException: The type initializer for 'Mutagen.Bethesda.Plugins.Meta.GameConstants' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Mutagen.Bethesda.Strings.DI.MutagenEncoding' threw an exception.
 ---> System.IO.FileNotFoundException: 
File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Mutagen.Bethesda.Strings.DI.MutagenEncoding..cctor()
   --- End of inner exception stack trace ---
   at Mutagen.Bethesda.Plugins.Meta.GameConstants..cctor()
   --- End of inner exception stack trace ---
   at Mutagen.Bethesda.Plugins.Meta.GameConstants.Get(GameRelease release)
   at Mutagen.Bethesda.Plugins.Meta.GameConstants.op_Implicit(GameRelease mode)
   at Mutagen.Bethesda.Skyrim.SkyrimModBinaryOverlay.SkyrimModFactory(ModPath path, SkyrimRelease release, StringsReadParameters stringsParam, IFileSystem fileSystem, Boolean throwOnUnknownSubrecord)
```
which was fixed by wiping the temp folder

Also write docs about the temp folder concept, and wiping it in the troubleshoot section

**Comment by Noggog** [comment]
Will reopen if it comes up again
