### ISSUE TITLE
Spriggit v0.27.0 - Starfield - unable to serialize SFBGS004.esm, Starfield.esm - BGSVehicleConfig

### ISSUE THREAD

**Issue by JasonJShuler** [Mutagen-Modding/Spriggit#88]
When I attempt to serialize the vanilla starfield .esms, I am unable to serialize SFBGS004.esm - the file containing the vehicle.

(The other "extra" vanilla esms all seem to work fine; still waiting on starfield.esm)

Here is the relevant error

```
2024-09-05 13:07:00.230 -04:00 [ERR] Error syncing to Git
Mutagen.Bethesda.Serialization.Exceptions.FilePathedException: Exception occurred while processing related to a filepath: C:\a1_esm_dump\SFBGS004\RecordData.yaml
 ---> SubrecordException  => Rev8 (000033:SFBGS004.esm<Furniture>) => BFCB: Requested value 'BGSVehicleConfig' was not found. System.ArgumentException: Requested value 'BGSVehicleConfig' was not found.
   at System.Enum.TryParseByName[TStorage](RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, TStorage& result)
   at System.Enum.TryParseByValueOrName[TUnderlying,TStorage](RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, TUnderlying& result)
   at System.Enum.Parse[TEnum](String value, Boolean ignoreCase)
   at System.Enum.Parse[TEnum](String value)
   at Mutagen.Bethesda.Starfield.AComponent.GetComponentType(SubrecordFrame bfcb)
   at Mutagen.Bethesda.Starfield.AComponentBinaryOverlay.AComponentFactory(OverlayStream stream, BinaryOverlayFactoryPackage package, TypedParseParams translationParams)
   at Mutagen.Bethesda.Plugins.Binary.Overlay.PluginBinaryOverlay.<>c__DisplayClass32_0`1.<ParseRepeatedTypelessSubrecord>b__0(OverlayStream s, RecordType r, BinaryOverlayFactoryPackage p, TypedParseParams recConv)
   at Mutagen.Bethesda.Plugins.Binary.Overlay.PluginBinaryOverlay.ParseRepeatedTypelessSubrecord[T](OverlayStream stream, RecordTriggerSpecs trigger, StreamTypedFactory`1 factory, TypedParseParams translationParams)
   at Mutagen.Bethesda.Plugins.Binary.Overlay.PluginBinaryOverlay.ParseRepeatedTypelessSubrecord[T](OverlayStream stream, RecordTriggerSpecs trigger, ConverterFactory`1 factory, TypedParseParams translationParams)
   at Mutagen.Bethesda.Starfield.FurnitureBinaryOverlay.FillRecordType(OverlayStream stream, Int32 finalPos, Int32 offset, RecordType type, PreviousParse lastParsed, Dictionary`2 recordParseCount, TypedParseParams translationParams)
   at Mutagen.Bethesda.Plugins.Binary.Overlay.PluginBinaryOverlay.FillSubrecordTypes(OverlayStream stream, Int32 finalPos, Int32 offset, TypedParseParams translationParams, RecordTypeFillWrapper fill)   at Mutagen.Bethesda.Plugins.Records.GroupMajorRecordCacheWrapper`1.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Noggog.EnumerableExt.WithIndex[T](IEnumerable`1 en)+MoveNext() in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Extensions\EnumerableExt.cs:line 223
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Noggog.WorkEngine.InlineWorkDropoff.EnqueueAndWait[T](IEnumerable`1 items, Func`2 action, CancellationToken cancellationToken) in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\WorkEngine\InlineWorkDropoff.cs:line 76
   at Mutagen.Bethesda.Serialization.Utility.SerializationHelper.WriteFilePerRecord[TKernel,TWriteObject,TGroup,TObject](StreamPackage streamPackage, TGroup group, String fieldName, SerializationMetaData metaData, MutagenSerializationWriterKernel`2 kernel, WriteAsync`3 groupWriter, HasSerializationItems`1 groupHasSerializationItems, WriteAsync`3 itemWriter, Boolean withNumbering)
   at Mutagen.Bethesda.Starfield.StarfieldMod_Serialization.SerializeFields[TKernel,TWriteObject](TWriteObject writer, IStarfieldModGetter item, MutagenSerializationWriterKernel`2 kernel, SerializationMetaData metaData) in D:\a\Spriggit\Spriggit\Translation Packages\Spriggit.Yaml.Starfield\obj\Release\net8.0\Mutagen.Bethesda.Serialization.SourceGenerator\Mutagen.Bethesda.Serialization.SourceGenerator.Serialization.SerializationSourceGenerator\StarfieldMod_Serializations.g.cs:line 1831
   at Mutagen.Bethesda.Starfield.StarfieldMod_Serialization.Serialize[TKernel,TWriteObject](TWriteObject writer, IStarfieldModGetter item, MutagenSerializationWriterKernel`2 kernel, IWorkDropoff workDropoff, IFileSystem fileSystem, ICreateStream streamCreator, CancellationToken cancel) in D:\a\Spriggit\Spriggit\Translation Packages\Spriggit.Yaml.Starfield\obj\Release\net8.0\Mutagen.Bethesda.Serialization.SourceGenerator\Mutagen.Bethesda.Serialization.SourceGenerator.Serialization.SerializationSourceGenerator\StarfieldMod_Serializations.g.cs:line 36
   at Mutagen.Bethesda.Serialization.Yaml.MutagenYamlConverterStarfieldModMixIns.SerializeInternal[TMeta](MutagenYamlConverter converterBootstrap, IStarfieldModGetter item, DirectoryPath path, IWorkDropoff workDropoff, IFileSystem fileSystem, ICreateStream streamCreator, TMeta extraMeta, WriteAsync`3 metaWriter, Nullable`1 cancel) in D:\a\Spriggit\Spriggit\Translation Packages\Spriggit.Yaml.Starfield\obj\Release\net8.0\Mutagen.Bethesda.Serialization.SourceGenerator\Mutagen.Bethesda.Serialization.SourceGenerator.Serialization.SerializationSourceGenerator\MutagenYamlConverter_StarfieldMod_MixIns.g.cs:line 48
```

Update: Turns out it is the same record type causing it to choke on Starfield.esm -- it's on the player record so not sure how far it made it

```
2024-09-05 13:09:34.778 -04:00 [INF] Starting to serialize from Starfield.esm => C:\Program Files (x86)\Steam\steamapps\common\Starfield\Data\Starfield.esm to C:\a1_esm_dump\Starfield with SpriggitMeta { Source = Spriggit.Yaml.Starfield.0.27.0, Release = Starfield }
2024-09-05 13:20:51.172 -04:00 [ERR] Error syncing to Git
Mutagen.Bethesda.Serialization.Exceptions.FilePathedException: Exception occurred while processing related to a filepath: C:\a1_esm_dump\Starfield\RecordData.yaml
 ---> SubrecordException  => Player (000007:Starfield.esm<Npc>) => BFCB: Requested value 'BGSVehicleManagement' was not found. System.ArgumentException: Requested value 'BGSVehicleManagement' was not found.
   at System.Enum.TryParseByName[TStorage](RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, TStorage& result)
...
```

Thanks!

**Comment by Noggog** [comment]
Mutagen definitions updated.  Will roll out with next version

**Comment by JMPZ11** [comment]
This issue is still happening with Spriggit 0.30.0

**Comment by JMPZ11** [comment]
> Mutagen definitions updated. Will roll out with next version

So sorry to bother - is there like a way to manually build it to use the new definitions?
