### ISSUE TITLE
Spriggit 0.30.0 still unable to serialize Rover records: Requested value 'BGSVehicleConfig' was not found

### ISSUE THREAD

**Issue by JMPZ11** [Mutagen-Modding/Spriggit#93]
Technically a dup of #88 re v 0.27.0 closed as fixed in next release, but it doesn't seem to be fixed, and I cannot reopen the old issue, apologies for the clutter.

Definitely would be nice to be able to handle custom rovers in Spriggit :)

```
2024-09-24 15:07:56.171 -04:00 [INF] Getting entry point for SpriggitMeta { Source = Spriggit.Yaml.Starfield.0.30.0, Release = Starfield }
2024-09-24 15:07:56.171 -04:00 [INF] Starting to serialize from SFBGS004.esm => C:\Program Files (x86)\Steam\steamapps\common\Starfield\Data\SFBGS004.esm to C:\a1_esm_dump\SFBGS004 with SpriggitMeta { Source = Spriggit.Yaml.Starfield.0.30.0, Release = Starfield }
2024-09-24 15:07:57.585 -04:00 [ERR] Error syncing to Git
Mutagen.Bethesda.Serialization.Exceptions.FilePathedException: Exception occurred while processing related to a filepath: C:\a1_esm_dump\SFBGS004\RecordData.yaml
 ---> SubrecordException  => Rev8 (000033:SFBGS004.esm<Furniture>) => BFCB: Requested value 'BGSVehicleConfig' was not found. System.ArgumentException: Requested value 'BGSVehicleConfig' was not found.
   at System.Enum.TryParseByName[TStorage](RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, TStorage& result)
   at System.Enum.TryParseByValueOrName[TUnderlying,TStorage](RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, TUnderlying& result)
   at Mutagen.Bethesda.Starfield.AComponentBinaryOverlay.AComponentFactory(OverlayStream stream, BinaryOverlayFactoryPackage package, TypedParseParams translationParams)
   at Mutagen.Bethesda.Plugins.Binary.Overlay.PluginBinaryOverlay.ParseRepeatedTypelessSubrecord[T](OverlayStream stream, RecordTriggerSpecs trigger, StreamTypedFactory`1 factory, TypedParseParams translationParams)
   at Mutagen.Bethesda.Starfield.FurnitureBinaryOverlay.FillRecordType(OverlayStream stream, Int32 finalPos, Int32 offset, RecordType type, PreviousParse lastParsed, Dictionary`2 recordParseCount, TypedParseParams translationParams)
   at Mutagen.Bethesda.Plugins.Binary.Overlay.PluginBinaryOverlay.FillSubrecordTypes(OverlayStream stream, Int32 finalPos, Int32 offset, TypedParseParams translationParams, RecordTypeFillWrapper fill)   at Mutagen.Bethesda.Plugins.Records.GroupMajorRecordCacheWrapper`1.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Noggog.EnumerableExt.WithIndex[T](IEnumerable`1 en)+MoveNext() in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Extensions\EnumerableExt.cs:line 223
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Noggog.WorkEngine.InlineWorkDropoff.EnqueueAndWait[T](IEnumerable`1 items, Func`2 action, CancellationToken cancellationToken) in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\WorkEngine\InlineWorkDropoff.cs:line 76
   at Mutagen.Bethesda.Serialization.Utility.SerializationHelper.WriteFilePerRecord[TKernel,TWriteObject,TGroup,TObject](StreamPackage streamPackage, TGroup group, String fieldName, SerializationMetaData metaData, MutagenSerializationWriterKernel`2 kernel, WriteAsync`3 groupWriter, HasSerializationItems`1 groupHasSerializationItems, WriteAsync`3 itemWriter, Boolean withNumbering)
   at Mutagen.Bethesda.Starfield.StarfieldMod_Serialization.SerializeFields[TKernel,TWriteObject](TWriteObject writer, IStarfieldModGetter item, MutagenSerializationWriterKernel`2 kernel, SerializationMetaData metaData) in D:\a\Spriggit\Spriggit\Translation Packages\Spriggit.Yaml.Starfield\obj\Release\net8.0\Mutagen.Bethesda.Serialization.SourceGenerator\Mutagen.Bethesda.Serialization.SourceGenerator.Serialization.SerializationSourceGenerator\StarfieldMod_Serializations.g.cs:line 1831
   at Mutagen.Bethesda.Starfield.StarfieldMod_Serialization.Serialize[TKernel,TWriteObject](TWriteObject writer, IStarfieldModGetter item, MutagenSerializationWriterKernel`2 kernel, IWorkDropoff workDropoff, IFileSystem fileSystem, ICreateStream streamCreator, CancellationToken cancel) in D:\a\Spriggit\Spriggit\Translation Packages\Spriggit.Yaml.Starfield\obj\Release\net8.0\Mutagen.Bethesda.Serialization.SourceGenerator\Mutagen.Bethesda.Serialization.SourceGenerator.Serialization.SerializationSourceGenerator\StarfieldMod_Serializations.g.cs:line 36
   at Mutagen.Bethesda.Serialization.Yaml.MutagenYamlConverterStarfieldModMixIns.SerializeInternal[TMeta](MutagenYamlConverter converterBootstrap, IStarfieldModGetter item, DirectoryPath path, IWorkDropoff workDropoff, IFileSystem fileSystem, ICreateStream streamCreator, TMeta extraMeta, WriteAsync`3 metaWriter, Nullable`1 cancel) in D:\a\Spriggit\Spriggit\Translation Packages\Spriggit.Yaml.Starfield\obj\Release\net8.0\Mutagen.Bethesda.Serialization.SourceGenerator\Mutagen.Bethesda.Serialization.SourceGenerator.Serialization.SerializationSourceGenerator\MutagenYamlConverter_StarfieldMod_MixIns.g.cs:line 48
   --- End of inner exception stack trace ---

```

Thanks!

**Comment by JMPZ11** [comment]
This is rapidly becoming a bigger and bigger problem as the moment a vehicle is involved, I can't spriggit anymore. And the vehicle records are getting more and more popular...

Thanks so much!

**Comment by Noggog** [comment]
Yeah, I hear you.  All I think can be done is update as quick as possible.  (Sorry about not including that specifically in the last release.. cant remember exactly how it didn't make it in).    Shattered Space coming out was a curveball that made it take a bit longer than normal. 

Give 0.31 a spin and let me know how they do for you
