### ISSUE TITLE
Spriggit v0.35.0+6b6144004 errors exporting starfield.esm

### ISSUE THREAD

**Issue by JMPZ11** [Mutagen-Modding/Spriggit#95]
I'm pretty sure at one point it had been able to serialize it without errors I thought...

This same error I think was present in the Spriggit released with vehicle support. It seems to be related to navmeshes, which CK still can't output valid navinfo blocks... So no clue if it's realated to that or what.

Good news is it can serialized all the other vanilla esms, including Shatttered Space! That is awesome!

Thanks!

```
Mutagen.Bethesda.Serialization.Exceptions.FilePathedException: Exception occurred while processing related to a filepath: C:\a1_esm_dump\Starfield\RecordData.yaml
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Mutagen.Bethesda.Starfield.NavigationMesh_Serialization.SerializeFields[TKernel,TWriteObject](TWriteObject writer, INavigationMeshGetter item, MutagenSerializationWriterKernel`2 kernel, SerializationMetaData metaData) in D:\a\Spriggit\Spriggit\Translation Packages\Spriggit.Yaml.Starfield\obj\Release\net8.0\Mutagen.Bethesda.Serialization.SourceGenerator\Mutagen.Bethesda.Serialization.SourceGenerator.Serialization.SerializationSourceGenerator\NavigationMesh_Serializations.g.cs:line 77
   at Mutagen.Bethesda.Starfield.NavigationMesh_Serialization.Serialize[TKernel,TWriteObject](TWriteObject writer, INavigationMeshGetter item, MutagenSerializationWriterKernel`2 kernel, SerializationMetaData metaData) in D:\a\Spriggit\Spriggit\Translation Packages\Spriggit.Yaml.Starfield\obj\Release\net8.0\Mutagen.Bethesda.Serialization.SourceGenerator\Mutagen.Bethesda.Serialization.SourceGenerator.Serialization.SerializationSourceGenerator\NavigationMesh_Serializations.g.cs:line 32
   at Mutagen.Bethesda.Serialization.Yaml.YamlSerializationWriterKernel.WriteLoqui[TKernel,TObject](MutagenSerializationWriterKernel`2 kernel, YamlWritingUnit writer, String fieldName, TObject item, SerializationMetaData serializationMetaData, WriteAsync`3 writeCall)
   at Mutagen.Bethesda.Serialization.MutagenSerializationWriterKernel`2.WriteLoqui[TObject](TWriterObject writer, String fieldName, TObject item, SerializationMetaData serializationMetaData, WriteAsync`3 writeCall)
   at Mutagen.Bethesda.Starfield.Cell_Serialization.SerializeFields[TKernel,TWriteObject](TWriteObject writer, ICellGetter item, MutagenSerializationWriterKernel`2 kernel, SerializationMetaData metaData) in D:\a\Spriggit\Spriggit\Translation Packages\Spriggit.Yaml.Starfield\obj\Release\net8.0\Mutagen.Bethesda.Serialization.SourceGenerator\Mutagen.Bethesda.Serialization.SourceGenerator.Serialization.SerializationSourceGenerator\Cell_Serializations.g.cs:line 148
   at Mutagen.Bethesda.Starfield.Cell_Serialization.Serialize[TKernel,TWriteObject](TWriteObject writer, ICellGetter item, MutagenSerializationWriterKernel`2 kernel, SerializationMetaData metaData) in D:\a\Spriggit\Spriggit\Translation Packages\Spriggit.Yaml.Starfield\obj\Release\net8.0\Mutagen.Bethesda.Serialization.SourceGenerator\Mutagen.Bethesda.Serialization.SourceGenerator.Serialization.SerializationSourceGenerator\Cell_Serializations.g.cs:line 33
   at Mutagen.Bethesda.Serialization.Utility.SerializationHelper.<>c__DisplayClass4_2`6.<<AddBlocksToWork>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Serialization.Utility.SerializationHelper.<>c__DisplayClass4_2`6.<<AddBlocksToWork>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at Noggog.WorkEngine.InlineWorkDropoff.EnqueueAndWait[T](IEnumerable`1 items, Func`2 action, CancellationToken cancellationToken) in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\WorkEngine\InlineWorkDropoff.cs:line 77
   at Mutagen.Bethesda.Serialization.Utility.SerializationHelper.<>c__DisplayClass4_1`6.<<AddBlocksToWork>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Noggog.WorkEngine.InlineWorkDropoff.EnqueueAndWait[T](IEnumerable`1 items, Func`2 action, CancellationToken cancellationToken) in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\WorkEngine\InlineWorkDropoff.cs:line 77
   at Mutagen.Bethesda.Serialization.Utility.SerializationHelper.<>c__DisplayClass4_0`6.<<AddBlocksToWork>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Noggog.WorkEngine.InlineWorkDropoff.EnqueueAndWait[T](IEnumerable`1 items, Func`2 action, CancellationToken cancellationToken) in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\WorkEngine\InlineWorkDropoff.cs:line 77
   at Mutagen.Bethesda.Serialization.Utility.SerializationHelper.AddBlocksToWork[TKernel,TWriteObject,TGroup,TBlock,TSubBlock,TMajor](StreamPackage streamPackage, TGroup obj, String fieldName, Func`2 blockRetriever, Func`2 subBlockRetriever, Func`2 majorRetriever, Func`2 blockNumberRetriever, Func`2 subBlockNumberRetriever, SerializationMetaData metaData, MutagenSerializationWriterKernel`2 kernel, WriteAsync`3 metaWriter, HasSerializationItems`1 metaHasSerialization, WriteAsync`3 blockWriter, HasSerializationItems`1 blockHasSerialization, WriteAsync`3 subBlockWriter, HasSerializationItems`1 subBlockHasSerialization, WriteAsync`3 majorWriter, Boolean withNumbering)
   at Mutagen.Bethesda.Starfield.StarfieldMod_Serialization.SerializeFields[TKernel,TWriteObject](TWriteObject writer, IStarfieldModGetter item, MutagenSerializationWriterKernel`2 kernel, SerializationMetaData metaData) in D:\a\Spriggit\Spriggit\Translation Packages\Spriggit.Yaml.Starfield\obj\Release\net8.0\Mutagen.Bethesda.Serialization.SourceGenerator\Mutagen.Bethesda.Serialization.SourceGenerator.Serialization.SerializationSourceGenerator\StarfieldMod_Serializations.g.cs:line 1841
   at Mutagen.Bethesda.Starfield.StarfieldMod_Serialization.Serialize[TKernel,TWriteObject](TWriteObject writer, IStarfieldModGetter item, MutagenSerializationWriterKernel`2 kernel, IWorkDropoff workDropoff, IFileSystem fileSystem, ICreateStream streamCreator, CancellationToken cancel) in D:\a\Spriggit\Spriggit\Translation Packages\Spriggit.Yaml.Starfield\obj\Release\net8.0\Mutagen.Bethesda.Serialization.SourceGenerator\Mutagen.Bethesda.Serialization.SourceGenerator.Serialization.SerializationSourceGenerator\StarfieldMod_Serializations.g.cs:line 36
   at Mutagen.Bethesda.Serialization.Yaml.MutagenYamlConverterStarfieldModMixIns.SerializeInternal[TMeta](MutagenYamlConverter converterBootstrap, IStarfieldModGetter item, DirectoryPath path, IWorkDropoff workDropoff, IFileSystem fileSystem, ICreateStream streamCreator, TMeta extraMeta, WriteAsync`3 metaWriter, Nullable`1 cancel) in D:\a\Spriggit\Spriggit\Translation Packages\Spriggit.Yaml.Starfield\obj\Release\net8.0\Mutagen.Bethesda.Serialization.SourceGenerator\Mutagen.Bethesda.Serialization.SourceGenerator.Serialization.SerializationSourceGenerator\MutagenYamlConverter_StarfieldMod_MixIns.g.cs:line 48
   --- End of inner exception stack trace ---
   at Mutagen.Bethesda.Serialization.Yaml.MutagenYamlConverterStarfieldModMixIns.SerializeInternal[TMeta](MutagenYamlConverter converterBootstrap, IStarfieldModGetter item, DirectoryPath path, IWorkDropoff workDropoff, IFileSystem fileSystem, ICreateStream streamCreator, TMeta extraMeta, WriteAsync`3 metaWriter, Nullable`1 cancel) in D:\a\Spriggit\Spriggit\Translation Packages\Spriggit.Yaml.Starfield\obj\Release\net8.0\Mutagen.Bethesda.Serialization.SourceGenerator\Mutagen.Bethesda.Serialization.SourceGenerator.Serialization.SerializationSourceGenerator\MutagenYamlConverter_StarfieldMod_MixIns.g.cs:line 53
   at Mutagen.Bethesda.Serialization.Yaml.MutagenYamlConverterStarfieldModMixIns.Serialize(MutagenYamlConverter converterBootstrap, IStarfieldModGetter item, DirectoryPath path, SpriggitSource extraMeta, IWorkDropoff workDropoff, IFileSystem fileSystem, ICreateStream streamCreator, Nullable`1 cancel) in D:\a\Spriggit\Spriggit\Translation Packages\Spriggit.Yaml.Starfield\obj\Release\net8.0\Mutagen.Bethesda.Serialization.SourceGenerator\Mutagen.Bethesda.Serialization.SourceGenerator.Serialization.SerializationSourceGenerator\MutagenYamlConverter_StarfieldMod_MixIns.g.cs:line 89
   at Spriggit.Yaml.Starfield.EntryPoint.Serialize(ModPath modPath, DirectoryPath outputDir, Nullable`1 dataPath, KnownMaster[] knownMasters, GameRelease release, IWorkDropoff workDropoff, IFileSystem fileSystem, ICreateStream streamCreator, SpriggitSource meta, CancellationToken cancel) in D:\a\Spriggit\Spriggit\Translation Packages\Spriggit.Yaml.Starfield\EntryPoint.cs:line 42
   at Spriggit.Core.DynamicEntryPoint.Serialize(ModPath modPath, DirectoryPath outputDir, Nullable`1 dataPath, KnownMaster[] knownMasters, GameRelease release, IWorkDropoff workDropoff, IFileSystem fileSystem, ICreateStream streamCreator, SpriggitSource meta, CancellationToken cancel) in D:\a\Spriggit\Spriggit\Spriggit.Core\DynamicEntryPoint.cs:line 53
   at Spriggit.Engine.AssemblyLoadedEntryPoint.Serialize(ModPath modPath, DirectoryPath outputDir, Nullable`1 dataPath, KnownMaster[] knownMasters, GameRelease release, IWorkDropoff workDropoff, IFileSystem fileSystem, ICreateStream streamCreator, SpriggitSource meta, CancellationToken cancel) in D:\a\Spriggit\Spriggit\Spriggit.Engine\AssemblyLoadedEntryPoint.cs:line 41
   at Spriggit.Engine.Services.Singletons.SpriggitEngine.Serialize(ModPath bethesdaPluginPath, DirectoryPath outputFolder, Nullable`1 dataPath, Boolean postSerializeChecks, IEngineEntryPoint entryPt, SpriggitMeta meta, Nullable`1 cancel) in D:\a\Spriggit\Spriggit\Spriggit.Engine\Services\Singletons\SpriggetEngine.cs:line 66
   at Spriggit.UI.ViewModels.Transient.LinkVm.SyncToGit(CancellationToken cancel) in D:\a\Spriggit\Spriggit\Spriggit.UI\ViewModels\Transient\LinkVm.cs:line 251

```

**Comment by Noggog** [comment]
Sorry for the late reply!   Do you happen to have a copy of a mod that triggered this still?

**Comment by JMPZ11** [comment]
It is indeed starfield.esm -- I didn't look to see specifically what failed apologies I was rushing around.

I'm trying to export everything -- all the vanilla esms, so I can do searching and crhange tracking (eventually -- starfield.esm is too big for git, so I may be using perforce)

I would give my left wingnut for the ability to binary (or base64 or something) encode the sections it can't read or something.

**Comment by Noggog** [comment]
Will keep this open, but don't have any immediate plans on trying to get base esms to translate.  Would need a solid understanding of the use cases for wanting to do that.   Use case for spriggit is to version mods being developed, which base esms don't quite fall into that category.
