### ISSUE TITLE
Spriggit 0.35.1 - Deserialization failure

### ISSUE THREAD

**Issue by ZeeOgre** [Mutagen-Modding/Spriggit#96]
2024-12-05 22:41:04.900 -06:00 [INF] Syncing from Mod to Git. M:\SteamLibrary\steamapps\common\Starfield\Data\ZeeOgresOutpostTutorial_Part1_Leveling.esp -> M:\gitrepos\moddersmilk\zeeogre\mods\ZO_VashOutpostTutorial\esp.spriggit
2024-12-05 22:41:04.902 -06:00 [INF] Getting entry point for SpriggitMeta { Source = Spriggit.Yaml.Starfield.0.35.1, Release = Starfield }
2024-12-05 22:41:04.903 -06:00 [INF] Starting to serialize from ZeeOgresOutpostTutorial_Part1_Leveling.esp => M:\SteamLibrary\steamapps\common\Starfield\Data\ZeeOgresOutpostTutorial_Part1_Leveling.esp to M:\gitrepos\moddersmilk\zeeogre\mods\ZO_VashOutpostTutorial\esp.spriggit with SpriggitMeta { Source = Spriggit.Yaml.Starfield.0.35.1, Release = Starfield }
2024-12-05 22:41:08.911 -06:00 [ERR] Error syncing to Git
Mutagen.Bethesda.Serialization.Exceptions.FilePathedException: Exception occurred while processing related to a filepath: M:\gitrepos\moddersmilk\zeeogre\mods\ZO_VashOutpostTutorial\esp.spriggit\RecordData.yaml
 ---> SubrecordException ZeeOgresOutpostTutorial_Part1_Leveling.esp => zo_OTT_VF_Sumati (00263D:ZeeOgresOutpostTutorial_Part1_Leveling.esp<Faction>) => RNAM: Unexpected subrecord    at Mutagen.Bethesda.Plugins.Records.GroupMajorRecordCacheWrapper`1.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Noggog.EnumerableExt.WithIndex[T](IEnumerable`1 en)+MoveNext() in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Extensions\EnumerableExt.cs:line 223
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Noggog.WorkEngine.InlineWorkDropoff.EnqueueAndWait[T](IEnumerable`1 items, Func`2 action, CancellationToken cancellationToken) in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\WorkEngine\InlineWorkDropoff.cs:line 76
   at Mutagen.Bethesda.Serialization.Utility.SerializationHelper.WriteFilePerRecord[TKernel,TWriteObject,TGroup,TObject](StreamPackage streamPackage, TGroup group, String fieldName, SerializationMetaData metaData, MutagenSerializationWriterKernel`2 kernel, WriteAsync`3 groupWriter, HasSerializationItems`1 groupHasSerializationItems, WriteAsync`3 itemWriter, Boolean withNumbering)
   at Mutagen.Bethesda.Starfield.StarfieldMod_Serialization.SerializeFields[TKernel,TWriteObject](TWriteObject writer, IStarfieldModGetter item, MutagenSerializationWriterKernel`2 kernel, SerializationMetaData metaData) in D:\a\Spriggit\Spriggit\Translation Packages\Spriggit.Yaml.Starfield\obj\Release\net8.0\Mutagen.Bethesda.Serialization.SourceGenerator\Mutagen.Bethesda.Serialization.SourceGenerator.Serialization.SerializationSourceGenerator\StarfieldMod_Serializations.g.cs:line 1841
   at Mutagen.Bethesda.Starfield.StarfieldMod_Serialization.Serialize[TKernel,TWriteObject](TWriteObject writer, IStarfieldModGetter item, MutagenSerializationWriterKernel`2 kernel, IWorkDropoff workDropoff, IFileSystem fileSystem, ICreateStream streamCreator, CancellationToken cancel) in D:\a\Spriggit\Spriggit\Translation Packages\Spriggit.Yaml.Starfield\obj\Release\net8.0\Mutagen.Bethesda.Serialization.SourceGenerator\Mutagen.Bethesda.Serialization.SourceGenerator.Serialization.SerializationSourceGenerator\StarfieldMod_Serializations.g.cs:line 36
   at Mutagen.Bethesda.Serialization.Yaml.MutagenYamlConverterStarfieldModMixIns.SerializeInternal[TMeta](MutagenYamlConverter converterBootstrap, IStarfieldModGetter item, DirectoryPath path, IWorkDropoff workDropoff, IFileSystem fileSystem, ICreateStream streamCreator, TMeta extraMeta, WriteAsync`3 metaWriter, Nullable`1 cancel) in D:\a\Spriggit\Spriggit\Translation Packages\Spriggit.Yaml.Starfield\obj\Release\net8.0\Mutagen.Bethesda.Serialization.SourceGenerator\Mutagen.Bethesda.Serialization.SourceGenerator.Serialization.SerializationSourceGenerator\MutagenYamlConverter_StarfieldMod_MixIns.g.cs:line 48
   --- End of inner exception stack trace ---
   at Mutagen.Bethesda.Serialization.Yaml.MutagenYamlConverterStarfieldModMixIns.SerializeInternal[TMeta](MutagenYamlConverter converterBootstrap, IStarfieldModGetter item, DirectoryPath path, IWorkDropoff workDropoff, IFileSystem fileSystem, ICreateStream streamCreator, TMeta extraMeta, WriteAsync`3 metaWriter, Nullable`1 cancel) in D:\a\Spriggit\Spriggit\Translation Packages\Spriggit.Yaml.Starfield\obj\Release\net8.0\Mutagen.Bethesda.Serialization.SourceGenerator\Mutagen.Bethesda.Serialization.SourceGenerator.Serialization.SerializationSourceGenerator\MutagenYamlConverter_StarfieldMod_MixIns.g.cs:line 53
   at Mutagen.Bethesda.Serialization.Yaml.MutagenYamlConverterStarfieldModMixIns.Serialize(MutagenYamlConverter converterBootstrap, IStarfieldModGetter item, DirectoryPath path, SpriggitSource extraMeta, IWorkDropoff workDropoff, IFileSystem fileSystem, ICreateStream streamCreator, Nullable`1 cancel) in D:\a\Spriggit\Spriggit\Translation Packages\Spriggit.Yaml.Starfield\obj\Release\net8.0\Mutagen.Bethesda.Serialization.SourceGenerator\Mutagen.Bethesda.Serialization.SourceGenerator.Serialization.SerializationSourceGenerator\MutagenYamlConverter_StarfieldMod_MixIns.g.cs:line 89
   at Spriggit.Yaml.Starfield.EntryPoint.Serialize(ModPath modPath, DirectoryPath outputDir, Nullable`1 dataPath, KnownMaster[] knownMasters, GameRelease release, IWorkDropoff workDropoff, IFileSystem fileSystem, ICreateStream streamCreator, SpriggitSource meta, CancellationToken cancel) in D:\a\Spriggit\Spriggit\Translation Packages\Spriggit.Yaml.Starfield\EntryPoint.cs:line 42
   at Spriggit.Core.DynamicEntryPoint.Serialize(ModPath modPath, DirectoryPath outputDir, Nullable`1 dataPath, KnownMaster[] knownMasters, GameRelease release, IWorkDropoff workDropoff, IFileSystem fileSystem, ICreateStream streamCreator, SpriggitSource meta, CancellationToken cancel) in D:\a\Spriggit\Spriggit\Spriggit.Core\DynamicEntryPoint.cs:line 53
   at Spriggit.Engine.AssemblyLoadedEntryPoint.Serialize(ModPath modPath, DirectoryPath outputDir, Nullable`1 dataPath, KnownMaster[] knownMasters, GameRelease release, IWorkDropoff workDropoff, IFileSystem fileSystem, ICreateStream streamCreator, SpriggitSource meta, CancellationToken cancel) in D:\a\Spriggit\Spriggit\Spriggit.Engine\AssemblyLoadedEntryPoint.cs:line 41
   at Spriggit.Engine.Services.Singletons.SpriggitEngine.Serialize(ModPath bethesdaPluginPath, DirectoryPath outputFolder, Nullable`1 dataPath, Boolean postSerializeChecks, IEngineEntryPoint entryPt, SpriggitMeta meta, Nullable`1 cancel) in D:\a\Spriggit\Spriggit\Spriggit.Engine\Services\Singletons\SpriggetEngine.cs:line 66
   at Spriggit.UI.ViewModels.Transient.LinkVm.SyncToGit(CancellationToken cancel) in D:\a\Spriggit\Spriggit\Spriggit.UI\ViewModels\Transient\LinkVm.cs:line 251
   
   
   
   
![image](https://github.com/user-attachments/assets/4583b910-9326-421e-8805-d0cb1bb0c316)

**Comment by Noggog** [comment]
Thanks for the report!

Do you have a link to the mod in question?  Usually the easiest way to get the definitions added

**Comment by ZeeOgre** [comment]
It's one i'm building right now! 🙂

It isn't in a state yet where i'm ready to post it anywhere.

________________________________

**Comment by Noggog** [comment]
Fair enough.  Can you give me some more details then about the record in question?    I gotta update the code to dump more info on its own.... but in the meantime, what type of record is `zo_OTT_VF_Sumati`?   And you have any knowledge of what `RNAM` is on it?   Spriggit doesnt recognize `RNAM` for it... so it's throwing up loud and early so that you dont lose the content (as it doesnt know how to translate it)

**Comment by Noggog** [comment]
Documentation blurb about it, which you might've already seen
https://mutagen-modding.github.io/Spriggit/unexpected-records/

**Comment by ZeeOgre** [comment]
It's a vendor faction -- removed it from "production" anyway, but it was one of 5 I'd set upSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Justin Swanson ***@***.***> Date: 12/7/24  6:08 PM  (GMT-06:00) To: Mutagen-Modding/Spriggit ***@***.***> Cc: ZeeOgre ***@***.***>, Author ***@***.***> Subject: Re: [Mutagen-Modding/Spriggit] Spriggit 0.35.1 - Deserialization failure (Issue #96) 
Fair enough.  Can you give me some more details then about the record in question?    I gotta update the code to dump more info on its own.... but in the meantime, what type of record is zo_OTT_VF_Sumati?   And you have any knowledge of what RNAM is on it?   Spriggit doesnt recognize RNAM for it... so it's throwing up loud and early so that you dont lose the content (as it doesnt know how to translate it)

**Comment by Noggog** [comment]
Fixed in mutagen.  Will be in next spriggit release 
https://github.com/Mutagen-Modding/Mutagen/commit/8454e9e1482dea9cc8d6ef41c6f3278466bbd4f5
